### ISSUE TITLE
Possible performance regression using callbacks 2.5.0 > 3.0.1

### ISSUE THREAD

**Issue by timfish** [node-ffi-napi/node-ffi-napi#108]
We recently tried updating from 2.5.0 to 3.0.1 and noticed a ~4x increase in reported CPU usage. 

Roughly every second, we call into a method and pass a callback which is invoked shortly thereafter. On some machines our Electron app CPU usage while doing this has risen from <10% to >50% with the only change being the bump in `ffi-napi` version.

Is there anything obvious that might have caused this? What can I do to help track this down?

https://github.com/node-ffi-napi/node-ffi-napi/compare/v2.5.0...v3.0.1

**Comment by timfish** [comment]
I'm going to close this since I can no longer reproduce it!

Many thanks for your hard work maintaining all of ffi-napi!

**Comment by MaikonPanazzolo** [comment]
I was using the latest v4.0.3 and notice this issue, so I install the version 2.5 and solved for me

**Comment by darrenzo** [comment]
> I was using the latest v4.0.3 and notice this issue, so I install the version 2.5 and solved for me

My 4.x code is 

```
import { Function as ffiFunc } from 'ffi-napi';
import * as ref from 'ref-napi';
import * as refArrayDi from 'ref-array-di';
import * as refStructDi from 'ref-struct-di';

const refArray = refArrayDi(ref);
const refStruct = refStructDi(ref);

export const pointer = ref.refType;
export const cString = ref.types.CString;
```

And now I also want to change to the version 2.5, this is my settings:

```
"dependencies": {
    "bindings": "^1.5.0",
    "ffi-napi": "2.5.0",
    "ref-array-di": "^1.2.1",
    "ref-napi": "^1.5.2"
  },
  "devDependencies": {
    "@types/ffi-napi": "2.4.3",
    "@types/node": "16.11.26",
    "@types/ref-array-di": "^1.2.3",
    "@types/ref-napi": "^1.4.1",
    "@types/ref-struct-di": "^1.1.6",
    "ref-struct-di": "^1.1.0"
  }
```

Then my code should be? Could you please give me a example?   Thank you.

**Comment by darrenzo** [comment]
@MaikonPanazzolo

**Comment by MaikonPanazzolo** [comment]
Sure, I'm using this way in an Electron app

```
const ffi       = require("ffi-napi");
const ref       = require("ref-napi");
const Struct    = require("ref-struct-di")(ref);
```

```
  "dependencies": {
    "@nut-tree/nut-js": "^2.0.1",
    "axios": "^0.24.0",
    "dotenv": "^10.0.0",
    "extract-zip": "^2.0.1",
    "ffi-napi": "2.5",
    "find-process": "^1.4.7",
    "getmac": "^5.20.0",
    "ini": "^2.0.0",
    "macaddress": "^0.5.2",
    "mariadb": "^2.5.5",
    "node-firebird": "^1.0.0",
    "node-macaddress": "^0.2.4",
    "node-stream-zip": "^1.15.0",
    "robotjs": "^0.6.0",
    "screenshot-desktop": "^1.12.7",
    "sequelize": "^5.22.3",
    "socket.io-client": "^4.3.2",
    "uuid": "^8.3.2",
    "vkey": "^1.0.1",
    "win32-api": "^9.6.0",
    "winston": "^3.6.0"
  },
```

**Comment by darrenzo** [comment]
> Sure, I'm using this way in an Electron app
> 
> ```
> const ffi       = require("ffi-napi");
> const ref       = require("ref-napi");
> const Struct    = require("ref-struct-di")(ref);
> ```
> 
> ```
>   "dependencies": {
>     "@nut-tree/nut-js": "^2.0.1",
>     "axios": "^0.24.0",
>     "dotenv": "^10.0.0",
>     "extract-zip": "^2.0.1",
>     "ffi-napi": "2.5",
>     "find-process": "^1.4.7",
>     "getmac": "^5.20.0",
>     "ini": "^2.0.0",
>     "macaddress": "^0.5.2",
>     "mariadb": "^2.5.5",
>     "node-firebird": "^1.0.0",
>     "node-macaddress": "^0.2.4",
>     "node-stream-zip": "^1.15.0",
>     "robotjs": "^0.6.0",
>     "screenshot-desktop": "^1.12.7",
>     "sequelize": "^5.22.3",
>     "socket.io-client": "^4.3.2",
>     "uuid": "^8.3.2",
>     "vkey": "^1.0.1",
>     "win32-api": "^9.6.0",
>     "winston": "^3.6.0"
>   },
> ```

@MaikonPanazzolo thank you so much.
