### ISSUE TITLE
Dynamic Symbol Retrieval Error

### ISSUE THREAD

**Issue by vladshcherbin** [node-ffi-napi/node-ffi-napi#112]
Hey, I'm using [Airgram](https://github.com/airgram/airgram) in a Telegram bot app. It uses ffi-napi 3.1.0 inside, but gives me an error on start:

![image](https://user-images.githubusercontent.com/6711845/100847321-bade5500-3490-11eb-9b89-a665d942a0f7.png)

The code it's linking to is: 

```js
DynamicLibrary.prototype.get = function (symbol) {
  debug('dlsym()', symbol);
  assert.strictEqual('string', typeof symbol);

  const ptr = dlsym(this._handle, symbol);
  assert(Buffer.isBuffer(ptr));

  if (ptr.isNull()) {
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error());
  }

  ptr.name = symbol;

  return ptr;
}
```

Maybe you have any idea why this is happening? 🙏 Thanks

ffi-napi 3.1.0, mac os 10.14.6, node 14.15.1

**Comment by addaleax** [comment]
> Hey, I'm using [Airgram](https://github.com/airgram/airgram) in a Telegram bot app.

That’s probably where you’ll want to report this. I’ll close this issue, feel free to ping me if there is a concrete reason to believe that this is a problem with ffi-napi.
