### ISSUE TITLE
Undefined identifier in node-addon-api

### ISSUE THREAD

**Issue by sundong212** [node-ffi-napi/node-ffi-napi#115]
System: Windows 10
NodeJS version: 12.18.3
node-gyp: 7.1.0
ElectronJS: 11.0.4
electron-rebuild: 2.3.4
MSBuild: 15.0
ffi-napi: 3.0.1

**The message below is the error:** 
``c:\users\administrator\desktop\projectx\fusi-sdk\node\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(416)
: error C3861: “napi_is_date”: undefined identifier [C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-na
pi\build\ffi_bindings.vcxproj]
c:\users\administrator\desktop\projectx\fusi-sdk\node\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(711) : error C3861: “napi_create_date”: undefined identifier [C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ff
i-napi\build\ffi_bindings.vcxproj]
c:\users\administrator\desktop\projectx\fusi-sdk\node\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(728) : error C3861: “napi_get_date_value”:  undefined identifier [C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
c:\users\administrator\desktop\projectx\fusi-sdk\node\node_modules\ffi-napi\src\ffi.cc(11): error C3861: “napi_get_instance_data”:  undefined identifier [C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
c:\users\administrator\desktop\projectx\fusi-sdk\node\node_modules\ffi-napi\src\ffi.cc(347): error C3861: “napi_set_ins
tance_data”: undefined identifier [C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-napi'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: `1`
Error: node-gyp failed to rebuild 'C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\ffi-napi'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\Administrator\Desktop\projectX\fusi-sdk\node\node_modules\electron-rebuild\lib\src\module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)``

This is happening when electron-rebuild executing. Any help would be appreciated. Thank you very much!

**Comment by addaleax** [comment]
I think something is wrong with the electron headers or electron-rebuild in this case, as you can see it’s not only affecting ffi-napi but also node-addon-api.

**Comment by sundong212** [comment]
Is this because I am using `nan`?

**Comment by sundong212** [comment]
Solved. the electron version against which electron-rebuild build should be the electron version is using.

electron-rebuild -v=11.0.4
