### ISSUE TITLE
electron rebuild failure

### ISSUE THREAD

**Issue by cdburke** [node-ffi-napi/node-ffi-napi#133]
on windows 10, my electron build has started failing at ffi-napi rebuild. Versions are:

electron v11.2.3
npm 6.14.6
node v12.18.3

After the sequence:

npm install electron
npm install ffi-napi
npm install --save-dev electron-rebuild
node_modules\.bin\electron-rebuild.cmd --module-dir . -v 11.2.3

the build fails with:

~~~~
...
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.                                                                                    
\ Building module: ffi-napi, Completed: 0  nothing.c                                                                                                                                           
| Building module: ffi-napi, Completed: 0  win_delay_load_hook.cc                                                                                                                              
/ Building module: ffi-napi, Completed: 0  nothing.vcxproj -> C:\temp\node_modules\ffi-napi\build\Release\\nothing.lib                                                                         
- Building module: ffi-napi, Completed: 0  Assembling ..\..\..\deps\libffi\src\x86\win64_intel.S...                                                                                            
\ Building module: ffi-napi, Completed: 0..\..\..\deps\libffi\src\x86\win64_intel.S(1): error A2044: invalid character in file [C:\temp\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]   
..\..\..\deps\libffi\src\x86\win64_intel.S(2): error A2044: invalid character in file [C:\temp\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]                                            
...
~~~~

**Comment by indutny** [comment]
This sounds like it could be an `electron-rebuild` issue, to be honest. According to your report: `npm install ffi-napi` ends with success, right?

**Comment by doug-a-brunner** [comment]
I've started getting the same error with `electron-builder`. I also tried pulling down the source and building, with the same result:
```
> git clone https://github.com/node-ffi-napi/node-ffi-napi
> cd node-ffi-napi
> npm i
```
Manual runs of `node-gyp rebuild` produced the same error. I suspect a manual commit squash went wrong, because I see that commit `15997c1` contains a slightly different change to `deps/libffi/libffi.gyp:97` than `e09bb91`. The one that got released doesn't have the `/c` switch. I started a reinstall of my Windows build tools before noticing this, so I can't verify that this is the fix, but it seems worth looking at. This is the change:
```
diff --git a/deps/libffi/libffi.gyp b/deps/libffi/libffi.gyp
index a3f2281..787d443 100644
--- a/deps/libffi/libffi.gyp
+++ b/deps/libffi/libffi.gyp
@@ -94,7 +94,7 @@
               '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
             ],
             'action': [
-              '<@(ml)', '/Fo<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
+              '<@(ml)', '/c', '/Fo<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).obj',
                 '<(INTERMEDIATE_DIR)/<(RULE_INPUT_ROOT).asm',
             ],
             'message': 'Building assembly file <(RULE_INPUT_PATH)',
-- 
```

**Comment by doug-a-brunner** [comment]
What I described appears not to be the fix, but the problem seems to stem from trying to run the assembler on a file that hasn't gone through the preprocessor yet.

**Comment by indutny** [comment]
Interesting... So it happens on rebuild, but not during the initial build?

**Comment by indutny** [comment]
Wait, I just realized that `.S` should not be build with assembler at all. The `.gyp` config that we have preprocesses `.S` into `.asm` files to be used later with assembler.

**Comment by doug-a-brunner** [comment]
It seems that rule isn't getting invoked, and actually neither is the one following it; the terminal output just before the errors is `Assembling ..\..\..\deps\libffi\src\x86\win64_intel.S...`, where I would expect `Building assembly file ..\..\..\deps\libffi\src\x86\win64_intel.S` if the `build_asm` rule were running.

**Comment by Razviar** [comment]
In my case even attempt to install ffi-napi leads to big number of errors like this:

..\..\..\deps\libffi\src\x86\win64_intel.S(1): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(2): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(3): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(4): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(5): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(6): error A2044: invalid character in file [D:\mtgap\node_modules\ffi-napi\b
uild\deps\libffi\ffi.vcxproj]

**Comment by thmour** [comment]
It fails at install with those multiple error lines. I also tried to build from sources by cloning the git and running node-gyp rebuild at first i got `Error: Cannot find module 'get-uv-event-loop-napi-h'` then i got the same install error as razviar
```
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\kikos41\horticrafting-generator\node_modules\ffi-napi\build\Release\\nothing.lib
  Assembling ..\..\..\deps\libffi\src\x86\win64_intel.S...
..\..\..\deps\libffi\src\x86\win64_intel.S(1): error A2044: invalid character in file [C:\Users\kikos41\horticrafting-generator\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
..\..\..\deps\libffi\src\x86\win64_intel.S(2): error A2044: invalid character in file [C:\Users\kikos41\horticrafting-generator\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
```

**Comment by indutny** [comment]
Confirmed. Thank you for reporting!

You can follow the review process here: https://github.com/node-ffi-napi/node-ffi-napi/pull/136
