### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by zembrowski** [node-ffi-napi/node-ffi-napi#135]
I have issues with a C library which uses multi-threading internally.

While passing a pointer as an argument to a function I get the message:

> The Buffer was not created with this instance, but with instance "0x14000000020000"

The most strange thing is, that some functions of the C library use this pointer without an issue. Just one (the most important) has issues with it.

The C library can be used without any issues with FFI implementations in other languages.

I’ve read about Thread Safety in the libffi docs. How could I ensure only a single thread prepares a given ffi_cif?

Or, am I wrongly creating the pointer?

Here is a simplified example:

```js
var cache = StructType()
var cachePtr = ref.refType(cache)

var lib = ffi.Library('api.so', {
  'CreateBuffer': [cachePtr, []],
  'StartProcessing': ['int', [cachePtr]],
  'ReadBuffer': ['string', [cachePtr]]
})

var buffer = lib.CreateBuffer()
var run = lib.StartProcessing(buffer)

// error mentioned above

```

**Comment by addaleax** [comment]
I don’t think this has anything to do with thread safety, since you’re not using threads in any way?

**Comment by zembrowski** [comment]
Correct, I'm not using threads anywhere explicitly, but the C library uses threading internally and the error message I get indicates it has something to do with threads. Either that or some magic is happening while passing buffer to `lib.StartProcessing()`.

Got stuck for now. How could I dig deeper?

**Comment by addaleax** [comment]
But does the same work in plain C? If the C library uses threading *internally*, then that’s nothing that ffi-napi could do something about?

**Comment by zembrowski** [comment]
Yes, works perfectly with plain C, with C# and even PHP FFI (uses libffi). Due to the fact, that it works with PHP FFI I assume, that this issue is ffi-napi specific.

I wrote a minimal Node implementation to recreate my issue: https://github.com/zembrowski/neric-minimal

(`console.log(buffer)` shows me the correct memory address, as this is logged in eric.log)

**Comment by addaleax** [comment]
This:

> `'EricBearbeiteVorgang': ['int', ['string', 'string', 'int', structPrint, 'int', 'int', cachePtr, cachePtr]],`

does not match this:

> ```
> ERICAPI_IMPORT int STDCALL EricBearbeiteVorgang(
>        const char* datenpuffer,
>        const char* datenartVersion,
>        uint32_t bearbeitungsFlags,
>        const eric_druck_parameter_t* druckParameter,
>        const eric_verschluesselungs_parameter_t* cryptoParameter,
>        EricTransferHandle* transferHandle,
>        EricRueckgabepufferHandle rueckgabeXmlPuffer,
>        EricRueckgabepufferHandle serverantwortXmlPuffer);
> ```

It should work once these start matching.

**Comment by zembrowski** [comment]
Thank you for your responses. I really appreciate them.

I tried a lot of argument types for `EricBearbeiteVorgang`. Without any luck.

The one causing the error message is `EricRueckgabepufferHandle rueckgabeXmlPuffer`. `EricRueckgabepufferHandle` is a pointer to an opaque struct which fields I don’t know and the creator of the libraries doesn’t want to disclose.

How should I pass a correct pointer for it? (The header files contain all known definitions.)

**Comment by addaleax** [comment]
@zembrowski I mean, for starters, the number of parameters needs to be the same, you are missing an entry for `cryptoParameter` in your FFI description.

**Comment by zembrowski** [comment]
Thank you @addaleax. You are right. The FFI descriptions have to be very precise. Otherwise strange results might occur. I used [node-ffi-generate](https://github.com/node-ffi-packager/node-ffi-generate) to tackle this task.

This issue can be deleted, as it isn’t related to Thread Safety at all  and should be blamed to my starer-like skills.
