### ISSUE TITLE
ffi_bindings.node is not a valid win32 application in electron app

### ISSUE THREAD

**Issue by Sharcoux** [node-ffi-napi/node-ffi-napi#144]
I think that there is an issue with the build process for win platform. At least it is 100% reproducible with electron.

I created a minimal code that can reproduce the error. You can find the project [here](https://github.com/Sharcoux/electron-demo) and you can find the exe [here](https://drive.google.com/file/d/12zrAZnT33dfWeDCOABazWtI6InedzKrl/view?usp=sharing) if you want to see by yourself.

I'll present you the code quickly so that you can understand the issue.

The app was created with create-react-app. I removed everything unnecessary.

In `public/electron.js` you will find the minimal code needed to handle the electron app. You can ignore this file. Just note that it's calling 'ffi-napi' module.

In `src` you have just the app itself, which is just a 'Welcome' text

The electron build will rebuild all the node modules:

`  • rebuilding native dependencies  dependencies=ffi-napi@3.1.0, ref-napi@3.0.2, ref-napi@2.1.2 platform=win32 arch=x64`

The packaged app will work 100% fine on Mac and Linux, but on Windows I will get:

![image](https://user-images.githubusercontent.com/797545/113462373-d34f8380-9420-11eb-9daf-3ded3e33ae26.png)

I don't understand what's going on...

**Comment by xan105** [comment]
Did you rebuild `ffi-napi` and `ref-napi` with electron's headers using [electron-rebuild](https://www.npmjs.com/package/electron-rebuild) ?

**Comment by Sharcoux** [comment]
From what I understand, this what is happening when electron says: `• rebuilding native dependencies dependencies=ffi-napi@3.1.0, ref-napi@3.0.2, ref-napi@2.1.2 platform=win32 arch=x64`

Am I missing something?

**Comment by xan105** [comment]
Ok, sorry then I don't know ^_^ never had any problem loading _ffi-napi_ with electron by using _electron-rebuild_

**Comment by Sharcoux** [comment]
I tried to use electron-rebiuld to build ffi-napi and skip electron-builder's rebuild step by adding `npmRebuild: false` to the build config, but I still have the same issue. @xan105 Maybe you could show me how you would configure the minimal project I linked to make it work with electron-rebuild?

**Comment by xan105** [comment]
```
git clone https://github.com/Sharcoux/electron-demo
cd electron-demo
npm i
npm install --save-dev electron-rebuild
call node_modules\.bin\electron-rebuild.cmd //rebuilding native addon such as node-ffi-napi
npm run-script build //for react right ? sorry not familiar with it ^^
```
added in package.json to quickly run electron
```json
"scripts":{
  "run": "electron ." 
}
```

`npm run-script run`

![Sans titre](https://user-images.githubusercontent.com/14090532/113561966-90172f80-962f-11eb-903a-463d2932f8bb.png)

Is that the expected app ? No errors here in Windows 10 20H2 on app launch
Electron crashes when I click the 'start' button tho with exit status 4294930435

I can't really do more sorry I know nothing of react and thus your 'electron template' doesn't feel _minimal_ to me

**Comment by Sharcoux** [comment]
`yarn electron` is working fine. The issue is when you try to package the app with `yarn build-electron`. If you try to execute the app, it will show you the error I copied.

Don't worry about the react part. It won't reach there anyway. I's just that create-react-app is a good way to have an automatic configuration for webpack and babel without polluting too much the repo. I'll try to make it even more minimal

**Comment by Sharcoux** [comment]
The app will fail both with wine or in a native Windows environment.

Steps to reproduce on Linux

```
yarn install
yarn build-electron
wine ./dist/demo-electron\ Setup\ 0.1.0.exe
```

Steps to reproduce on Windows

```
yarn install
yarn build-electron
.\dist\demo-electron Setup 0.1.0.exe
```

**Comment by Sharcoux** [comment]
@xan105 You can update the project if you want. I made it even more minimal.

**Comment by Sharcoux** [comment]
Ok, so, apparently I'm the only monkey trying to build electron using electron-rebuild. So after a lib update, I got the same error but with `ref-napi` lib instead. I googled and found... My own unanswered topic.

I finally solved both issues and here is the solution. So here is a note for my future-self:

```js
const { execSync } = require('child_process')

;(() => {
  execSync('yarn run electron-builder install-app-deps --platform linux', {
    stdio: 'inherit',
  })

  execSync('yarn run electron-builder install-app-deps --platform win32', {
    stdio: 'inherit',
  })

  execSync('yarn run electron-builder install-app-deps --platform darwin', {
    stdio: 'inherit',
  })

  execSync(
    'yarn run node-gyp -C node_modules/ffi-napi clean configure --target_arch=x64 --target_platform=win32',
    { stdio: 'inherit' }
  )

  execSync(
    'yarn run node-gyp -C node_modules/ref-napi clean configure --target_arch=x64 --target_platform=win32',
    { stdio: 'inherit' }
  )
})()
```

Don't forget to keep `"npmRebuild": false,` in the "build" key in package.json. Run this as a pre-build step.
