### ISSUE TITLE
I cannot return the result of the .async function

### ISSUE THREAD

**Issue by afif-bouzid** [node-ffi-napi/node-ffi-napi#146]
Hello. I have a problem I cannot return the result of the console.log of the .async function to consume it elsewhere.
if i don't use .async nodejs will block until ffi-napi sends the result.
here is the function.

 ipcMain.handle('invoke-test' , (event, message ) => {

oduleyoneoPayement.ComValina_DLL_Payment.async(message, function  (err, res) {
  return res
  console.log(res)
})
    
    
})

**Comment by addaleax** [comment]
What exactly is your question?

**Comment by afif-bouzid** [comment]
Good morning anna
My problem is is that I can not return the result of the function when it is asynchronous.
I have undefined. I can't do .then or await.
in short, I can't export my result when it is asynchronous. and yet I see the result correctly in the console.log
Thank you.

**Comment by addaleax** [comment]
> I have undefined. I can't do .then or await.

If you are looking for Promises, maybe you are looking for something like `util.promisify`?

**Comment by afif-bouzid** [comment]
I need to string the value of my async function from the outside.
a bit like this:
but i get undefined
  (async function (){

 var test =  await ModuleyoneoPayement.ComValina_DLL_Payment.async(123, function (err, res) {
   console.log(res) // res correctly returns a value
 })
  
 console.log(test)  test return undefined
})()

**Comment by afif-bouzid** [comment]
Thanks Anna for your idea, I managed to get by with this piece of code.
my goal was to establish asynchronous communication between ffi-napi and the dom via an electron.js method.
I thank you for the quality of your contributions.
----------------------------------------------------------------------------------------------------------------------------
 ipcMain.on('synchronous-message', (event, arg) => {
          ModuleyoneoPayement.ComValina_DLL_Payment.async(arg, async function  (err, res) {
            event.returnValue = await res
          })

      })
