### ISSUE TITLE
中文路径报错 Error: Dynamic Linking Error: Win32 error 126

### ISSUE THREAD

**Issue by asd281533890** [node-ffi-napi/node-ffi-napi#154]
Dll的路径不能包含中文，否则会提示126错误，请问可以支持一下中文吗？非常感谢！
The dynamic link library in a path with Chinese like "C:\应用平台\myDll\myDllLib.dll" will report error: Dynamic Linking Error: Win32 error 126. Can author fix this? Thanks very much!

**Comment by lichaozhy** [comment]
It may be caused by '\'. Try '/' instead.

**Comment by asd281533890** [comment]
写相对路径就可以了,我之前也尝试过写相对路径但问题依旧,那是因为当时我写的相对路径是错的,我把dll的路径写成了相对于JS的路径.而正确的路径应该是相对于那个exe可执行文件的路径.因为JS是被exe编译后运行的,所以应该是相对于exe的路径
I fixed this by using relative path.I have tried this before but it doesn't work because I write the wrong path.The correct dll path should be relative to the exe executable file not the running JS.

**Comment by 1134506391** [comment]
> 写相对路径就可以了,我之前也尝试过写相对路径但问题依旧,那是因为当时我写的相对路径是错的,我把dll的路径写成了相对于JS的路径.而正确的路径应该是相对于那个exe可执行文件的路径.因为JS是被exe编译后运行的,所以应该是相对于exe的路径 I fixed this by using relative path.I have tried this before but it doesn't work because I write the wrong path.The correct dll path should be relative to the exe executable file not the running JS.

我有类似的问题，可以帮忙看看吗，谢谢，https://segmentfault.com/q/1010000044468877
