### ISSUE TITLE
No native build was found for the platform runtime error with electron

### ISSUE THREAD

**Issue by raviSussol** [node-ffi-napi/node-ffi-napi#157]
How to use this library with webpack in the electron js app? I have an electron js application that uses `ffi-napi` as a native module. The app works well if I don't include this library. And if I include this library in the app I've to modify node's global `__dirname` to true i.e. in the webpack config file: `node: {__dirname: true}`. This works well in the `development` mode. But when I build installer then starting an app would throws a runtime error:

```
Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=87 uv=1 libc=glibc node=14.16.0 electron=12.0.6 webpack=true
```

With a little bit research I found this library needs a node global __dirname to be set up but in `production` mode I'm clueless to find what path this library is expecting for. Or how to set correct path that this library needs in order to function properly? Any help would really be appreciated! Thanks.

**Comment by raviSussol** [comment]
Hi, can someone @all please help me on this? Here's my example repo: https://github.com/raviSussol/electron-webpack-native-module-example that demonstrate what has gone wrong.. I've tried many things but they all couldn't work at all. And this is really frustrating how to resolve it. I've found an issue with binding location in this library. Say in development I set `node: {__dirname: true}` in the webpack to get work and it works as well but when try to run the app from the installer then the above error throws.

**Comment by abjagtap** [comment]
@raviSussol Facing same issue

**Comment by raviSussol** [comment]
@abjagtap You can checkout the above repo to get working for you.

**Comment by ngiafeno** [comment]
@raviSussol how do you manage to not exclude the others dependencies using 'webpack-node-externals'

**Comment by raviSussol** [comment]
@ngiafeno You can either use `allowlist` key inside `nodeExternals()` function to exclude node modules using negation in regex from the bundle. Say, you want to exclude `ffi-napi` module from the bundle then:
```
const nodeExternals = require('webpack-node-externals');
module.exports = {
  externals: [nodeExternals({
    allowlist: [/^(?!(^(ffi-napi)$)).*$/i]
  })],
  ...
}
```

Or the simple of way of excluding node modules without using any plugins or libraries in the webpack:
```
externals: [
  function ({ _, request }, callback) {
    if (/(ffi-napi|ref-napi)$/.test(request)) {
      // Externalize to a commonjs module using the request path
      return callback(null, 'commonjs ' + request);
    }
    callback(); // Continue without externalizing the import
  }
]
```

**Comment by Taha-daboussi** [comment]
am facing the same issues , 
but i want to ship ffi-napi with the application 

this is my error 
`UnhandledPromiseRejectionWarning: Error: No native build was found for platform=win32 arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.21.2 webpack=true`
