### ISSUE TITLE
tsc throws TS2709 "Cannot use namespace 'StructType' as a type" on compilation

### ISSUE THREAD

**Issue by git-lmb** [node-ffi-napi/node-ffi-napi#160]
```
node_modules/@types/ffi-napi/index.d.ts:149:15 - error TS2709: Cannot use namespace 'StructType' as a type.
149: FFI_TYPE: StructType;
node_modules/@types/ffi-napi/index.d.ts:173:24 - error TS2709: Cannot use namespace 'StructType' as a type.
173: export const FFI_TYPE: StructType;
```

Current versions are `4.1.5` for `typescript` and `4.0.3` for `ffi-napi`. This issue started happening when I had to wipe my `node_modules` along with my package lock file and reinstall all packages in my current project - there were no version upgrades nor was `package.json` touched in any way. `ffi-napi` worked fine during `tsc` compilation before I decided to recreate my `node_modules` folder.

I tried several options that I found online, such as enabling synthetic imports in tsconfig, but there as nothing specific to `ffi-napi` nor did solutions for other projects work.

**Comment by addaleax** [comment]
This is an issue with `@types/ffi-napi`, not with this package here.
