### ISSUE TITLE
Dispatch manually main event loop

### ISSUE THREAD

**Issue by nwrkbiz** [node-ffi-napi/node-ffi-napi#166]
Hey guys. May be a silly question but I hope someone of you can give me a hint.

When calling a ffi function which takes over the thread, but is constantly executing a callback, is there a way to dispatch the nodejs event loop manually?

```
// tick will be a javascript callback passed via ffi
void takeOver(void (*tick)()){
  while(true) tick();
}
```

BR,
Giri

**Comment by LoganDark** [comment]
You can use async to execute the ffi function in a separate thread, that way it won't take over the node event loop

**Comment by nwrkbiz** [comment]
Thank you for the hint, I will test it.
