### ISSUE TITLE
Callback related crash?

### ISSUE THREAD

**Issue by repl-chris** [node-ffi-napi/node-ffi-napi#17]
I'm attempting to port an app from node-ffi to node-ffi-napi, and it appears to be a little crashy.  I've isolated and reproduced a crash which seems to be related to callbacks.  A small repro can be found here https://gist.github.com/repl-chris/8bc15d8ba1a8e9a88a93f7c791a1fa46 - it crashes within a few seconds using node-ffi-napi, and runs perfectly fine using node-ffi...I've reproduced it on windows 10 and windows server 2008 using node 8.9.  I was thinking perhaps the callback was getting GC'd but even keeping a reference to it on `global` does not help.  If I'm doing something wrong to cause this crash please let me know.

**Comment by bn3t** [comment]
I have the same problem with code that is using callbacks. The code works with node-ffi but not with ffi-napi. I get this error:

#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#

[1]    28584 segmentation fault  node lib/main.js

**Comment by bn3t** [comment]
In my case too, the callback is called from another thread. This normally [supported](https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#callbacks) by node-ffi which this library tries to replicate.

**Comment by woubuc** [comment]
So is this a bug and should we be able to use callbacks in threads, or is the documentation incorrect? @addaleax perhaps you can shed some light on this?

**Comment by bn3t** [comment]
IMHO this is bug because node-ffi supports it and it's doc is correct. For my project, I had to revert to node-ffi made compatible with node10 using [this branch](https://github.com/tagkiller/node-ffi/tree/feature/support_node10).
