### ISSUE TITLE
A vulnerability introduced by package node-addon-api

### ISSUE THREAD

**Issue by paimon0715** [node-ffi-napi/node-ffi-napi#170]
Hi, @addaleax @TooTallNate, there is a vulnerability introduced in your package **ffi-napi**:
### Issue Description
A vulnerability [**SNYK-JS-NODEADDONAPI-571001**](https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001) detected in package **node-addon-api(>=0.0.0 <1.7.2,>=2.0.0 <2.0.1)** is directly referenced by **_ffi-napi@2.5.0_**. We noticed that such a vulnerability has been removed since **_ffi-napi@3.0.0_**.
  
   However, ffi-napi's popular previous version **_ffi-napi@2.5.0_** ([9,886 downloads per week](https://www.npmjs.com/package/ffi-napi/v/2.5.0?activeTab=versions)) is still transitively referenced by a large amount of latest versions of active and popular downstream projects (about **92 downstream projects**, e.g., @hyperledger/node-vcx-wrapper 0.19.0-refactormove-test-agent-1912, @hyperledger/vcxagent-core 0.19.0-refactormove-test-agent-1912, @absaoss/node-vcx-wrapper 0.11.0-master-902, azure-iot-security-tpm 1.8.8, pano-tools 1.9.2, azure-iot-security-tpm@1.8.8, etc.).
As such, issue [**SNYK-JS-NODEADDONAPI-571001**](https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001) can be propagated into these downstream projects and expose security threats to them.
   
   These projects cannot easily upgrade **ffi-napi** from version **_2.5.0_** to _**(>=3.0.0)**_. For instance, **_ffi-napi@2.5.0_** is introduced into the above projects via the following package dependency paths:
(1)`azure-iot-security-tpm@1.8.8 ➔ tss.js@1.1.0 ➔ ffi-napi@2.5.0 ➔ node-addon-api@1.6.1`
    **......**
    
The projects such as **tss.js**, which introduced ffi-napi@2.5.0, are not maintained anymore. These unmaintained packages can neither upgrade **ffi-napi** nor be easily migrated by the large amount of affected downstream projects.  
 On behalf the downstream users, could you help us remove the vulnerability from package ffi-napi@2.5.0?

### Suggested Solution

Since these inactive projects set a version constaint **2.5.0** for **ffi-napi** on the above vulnerable dependency paths, if **ffi-napi** removes the vulnerability from 2.5.0 and releases a new patched version **_ffi-napi@2.5.1_**, such a vulnerability patch can be automatically propagated into the 92 affected downstream projects.

In **_ffi-napi@2.5.1_**, you can kindly try to perform the following upgrade:
`node-addon-api 1.6.1 ➔ 1.7.2`;  
**Note:**
**_node-addon-api@1.7.2_** has fixed the vulnerability ([**SNYK-JS-NODEADDONAPI-571001**](https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001))

Thanks again for your help.

Best regards,
Paimon

**Comment by addaleax** [comment]
@paimon0715 This vulnerability **only** comes into play when you’re on long-unsupported Node.js versions (pre-8.x), in which case you have bigger things to worry about anyway. Thanks for the report, but there’s nothing urgent to do here, I would say.
