### ISSUE TITLE
Is it possible to use C#/C++ class in DLL from node.js?

### ISSUE THREAD

**Issue by walsub** [node-ffi-napi/node-ffi-napi#191]
I am trying to use 3rd party library provided as a DLL file, and there are classes that I need to use. I am stuck in how to use classes in DLL from Node.js through ffi-napi. Can anyone tell me if it is possible and how plz?

**Comment by dev-flavioB** [comment]
i'm trying too with a custom c# dll, but isn't working. You find some B plan to this?

**Comment by walsub** [comment]
> i'm trying too with a custom c# dll, but isn't working. You find some B plan to this?

ffi-napi doesn't work for all DLL libraries. it supports method only library. we changed the way to use [node-addon-api](https://github.com/nodejs/node-addon-api) to integrate 3rd party libraries natively.
