### ISSUE TITLE
Not possible to pipe stdout from ffi C lib to node's console

### ISSUE THREAD

**Issue by jon-chuang** [node-ffi-napi/node-ffi-napi#193]
How to do this?

**Comment by addaleax** [comment]
What's your goal here? C libraries all share the same `stdout` stream, there is no way to redirect it without also affecting the rest of the process. If you need to do this, you'll need to load the library from a child process whose stdio you control.

**Comment by jon-chuang** [comment]
Actually, I realized the stdout from the ffi was piped to my terminal stdout when running node on a machine; unfortunately, it was a stdout of the child processes of the C code I was not seeing, whereas when calling from other language FFI tools, it would appear... I'll try to investigate but its unlikely that node-ffi is where the issue lies...
