### ISSUE TITLE
C frequently calls js through ffi.Callback, which will cause great performance problems

### ISSUE THREAD

**Issue by hexingcheng** [node-ffi-napi/node-ffi-napi#201]
I did a test on windows: the C code calls the js function 40 times in 1 second through ffi.Callback, the garbage collection will take a long time, and my js function does not have any business logic

**Comment by addaleax** [comment]
Why are you using FFI if performance is a concern? If you have a PR for improving performance, feel free to submit it, otherwise there doesn’t seem to be much to do here.
