### ISSUE TITLE
虚拟机中

### ISSUE THREAD

**Issue by buff-m** [node-ffi-napi/node-ffi-napi#205]
我使用ffi-napi调用dll，在win10，win11的物理机环境下是成功的，但放到 vmware 创建的 windows 虚拟机上就有问题，系统都是64位的

报错：Dynamic Linking Error: Win32 error 193

**Comment by buff-m** [comment]
原来是系统缺少运行库，解决了

**Comment by JaneYork** [comment]
> 
## 具体缺少什么运行库呢


windwos10 64位，账物理机，报错


  var ffi = require('ffi-napi')

  var libm = ffi.Library('libm', {
    'ceil': [ 'double', [ 'double' ] ]
  })
  console.log(libm.ceil(1.5)) // 2

**Comment by zard999** [comment]
> 原来是系统缺少运行库，解决了

你好，能告诉一下怎么看缺少哪些运行库吗？
