### ISSUE TITLE
Async call - can't get pointer data after resolve

### ISSUE THREAD

**Issue by themachho** [node-ffi-napi/node-ffi-napi#212]
Hello. Im working on an ExpressJS api that in one method it needs to comunicate with a DLL to obtain some information using the driver of a network printer.
According to the manufacturer (and also tested) if the printer is not in the same network or the printer is offline, the DLL tries to establish conection for 30secs until it returns controll to the process, so if im in another network (or printer offline) the DLL "hangs" for 30s. If im conected, the DLL response is instant. 

For that reason, and since i need to be able to handle other requests in parallel im trying to implement the async function of that DLL call.

This is the C++ function declaration. Receives the printer name (devName) and a pointer to store the information as JSON. Returns an int to indicate error_code/status. 
```C++
DLL_EXPORT_IMPORT int DLL_STD_CALL GetInformation(const char *devName, char *data);
```

DLLWrapper.js
```Javascript
var charPtr = ref.refType(ref.types.char); 
const DLLWrapper = new ffi.Library(dllPath, {
  GetInformation: ["int", ["string", charPtr]]
});
```
My current Normal/Blocking Call
```Javascript
  let ref = require("ref-napi");
  let information = Buffer.alloc(ref.sizeof.char * 1024);
  let errorCode = DLLWrapper.GetInformation(this.devName, information);
  return information.toString();
```
Response if connected. If offline, hangs for 30secs and returns error. 
```JSON
{
  "status": 5,
  "error": 3,
  "remaining_paper": 255,
  "has_errors": 1,
  "has_warnings": 1
}
```

Attept to use Async call
```Javascript
  let ref = require("ref-napi");
  let information = Buffer.alloc(ref.sizeof.char * 1024);
  let errorCode = CWWrapper.GetInformation.async(this.devName, information, (err, res) => {
      console.log(information);
  });
  return information.toString();
```
Response always, connected or disconnected. retVal = undefined
```JSON
{
  "status": 0,
  "error": 0,
  "remaining_paper": 0,
  "has_errors": 0,
  "has_warnings": 0
}
```

So it looks like the funcion is called but at the return the information is empty. Even if disconnected, the callback function is called instantly (and not after 30secs). If im connected, the callback is also called instantly but the information is empty also. 

Why is the callback called instantly? 
How can i call the DLL in a not blocking way so i can continue using the api during that "dead" time if the printer is not online?

**Comment by waitingsong** [comment]
```js
  let errorCode = CWWrapper.GetInformation.async(this.devName, information, (err, res) => {
      console.log(information);
  });
```

var `errorCode` is not expected , `res` is expected value
