### ISSUE TITLE
unable to install the module failing at the build step

### ISSUE THREAD

**Issue by mkundgol** [node-ffi-napi/node-ffi-napi#25]
Unable to install node-ffi-napi, failing for the last couple of days. It is failing at the build step with the below error and it seem to be coming from node-addon-api module

/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, int)’:
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3412:57: error: class ‘Napi::CallbackScope’ does not have any field named ‘_scope’
   napi_env env, napi_callback_scope scope) : _env(env), _scope(scope) {
                                                         ^
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, napi_async_context)’:
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3419:41: error: ‘_scope’ was not declared in this scope
       _env, Object::New(env), context, &_scope);
                                         ^
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3419:47: error: ‘napi_open_callback_scope’ was not declared in this scope
       _env, Object::New(env), context, &_scope);
                                               ^
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h: In destructor ‘virtual Napi::CallbackScope::~CallbackScope()’:
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3424:35: error: ‘_scope’ was not declared in this scope
   napi_close_callback_scope(_env, _scope);
                                   ^
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3424:41: error: ‘napi_close_callback_scope’ was not declared in this scope
   napi_close_callback_scope(_env, _scope);
                                         ^
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h: At global scope:
/home/asif/work/mq/node_modules/node-addon-api/napi-inl.h:3427:32: error: expected type-specifier before ‘napi_callback_scope’
 inline CallbackScope::operator napi_callback_scope() const {
                                ^
ffi_bindings.target.mk:107: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/asif/work/mq/node_modules/ffi-napi/build'

**Comment by mkundgol** [comment]
Looks like the recent updates in the node-addon-api (1.6.0) has caused this issue. Im not sure how long will they take to fix the problem. Can we pin the version of node-addon-api to 1.5.x pls as a workaround the build issue?

**Comment by addaleax** [comment]
@mkundgol Feel free to open a PR.

Did you include the full error output here? It feels like this shouldn’t be happening, and there’s something missing from your code.

Could you also share your Node.js and compiler versions, please?

**Comment by mkundgol** [comment]
@addaleax -
Node version
asif@bat1:~/l$ node -v
v6.9.4

compiler 
asif@bat1:~/l$ dpkg --list | grep compiler
ii  clang-4.0                           1:4.0-1ubuntu1~16.04.2                     amd64        C, C++ and Objective-C compiler (LLVM based)
ii  g++                                 4:5.3.1-1ubuntu1                           amd64        GNU C++ compiler
ii  g++-5                               5.4.0-6ubuntu1~16.04.10                    amd64        GNU C++ compiler
ii  gcc                                 4:5.3.1-1ubuntu1                           amd64        GNU C compiler
ii  gcc-5                               5.4.0-6ubuntu1~16.04.10                    amd64        GNU C compiler
ii  libllvm4.0:amd64                    1:4.0-1ubuntu1~16.04.2                     amd64        Modular compiler and toolchain technologies, runtime library
ii  llvm-4.0                            1:4.0-1ubuntu1~16.04.2                     amd64        Modular compiler and toolchain technologies
ii  llvm-4.0-dev                        1:4.0-1ubuntu1~16.04.2                     amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-4.0-runtime                    1:4.0-1ubuntu1~16.04.2                     amd64        Modular compiler and toolchain technologies, IR interpreter


Im just doing a simple npm install and here is the complete stack
asif@bat1:~/l$ npm install ffi-napi

> ref-napi@1.4.0 install /home/asif/l/node_modules/ref-napi
> node-gyp rebuild

make: Entering directory '/home/asif/l/node_modules/ref-napi/build'
  CXX(target) Release/obj.target/node-api/node_modules/node-addon-api/src/node_api.o
  CXX(target) Release/obj.target/node-api/node_modules/node-addon-api/src/node_internals.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/node-api.a
  COPY Release/node-api.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/asif/l/node_modules/ref-napi/build'

> ffi-napi@2.4.3 install /home/asif/l/node_modules/ffi-napi
> node-gyp rebuild

make: Entering directory '/home/asif/l/node_modules/ffi-napi/build'
  CXX(target) Release/obj.target/node-api/../node-addon-api/src/node_api.o
  CXX(target) Release/obj.target/node-api/../node-addon-api/src/node_internals.o
  AR(target) Release/obj.target/../node-addon-api/src/node-api.a
  COPY Release/node-api.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
../deps/libffi/src/closures.c:433:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.h:22:0,
                 from ../src/ffi.cc:1:
/home/asif/l/node_modules/node-addon-api/napi.h:1676:33: error: ‘napi_callback_scope’ has not been declared
     CallbackScope(napi_env env, napi_callback_scope scope);
                                 ^
/home/asif/l/node_modules/node-addon-api/napi.h:1680:14: error: expected type-specifier before ‘napi_callback_scope’
     operator napi_callback_scope() const;
              ^
/home/asif/l/node_modules/node-addon-api/napi.h:1687:5: error: ‘napi_callback_scope’ does not name a type
     napi_callback_scope _scope;
     ^
In file included from /home/asif/l/node_modules/node-addon-api/napi.h:1780:0,
                 from ../src/ffi.h:22,
                 from ../src/ffi.cc:1:
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3412:17: error: ‘napi_callback_scope’ has not been declared
   napi_env env, napi_callback_scope scope) : _env(env), _scope(scope) {
                 ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, int)’:
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3412:57: error: class ‘Napi::CallbackScope’ does not have any field named ‘_scope’
   napi_env env, napi_callback_scope scope) : _env(env), _scope(scope) {
                                                         ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, napi_async_context)’:
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3419:41: error: ‘_scope’ was not declared in this scope
       _env, Object::New(env), context, &_scope);
                                         ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3419:47: error: ‘napi_open_callback_scope’ was not declared in this scope
       _env, Object::New(env), context, &_scope);
                                               ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h: In destructor ‘virtual Napi::CallbackScope::~CallbackScope()’:
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3424:35: error: ‘_scope’ was not declared in this scope
   napi_close_callback_scope(_env, _scope);
                                   ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3424:41: error: ‘napi_close_callback_scope’ was not declared in this scope
   napi_close_callback_scope(_env, _scope);
                                         ^
/home/asif/l/node_modules/node-addon-api/napi-inl.h: At global scope:
/home/asif/l/node_modules/node-addon-api/napi-inl.h:3427:32: error: expected type-specifier before ‘napi_callback_scope’
 inline CallbackScope::operator napi_callback_scope() const {
                                ^
ffi_bindings.target.mk:107: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/asif/l/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/ibm/node-v6.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-133-generic
gyp ERR! command "/opt/ibm/node-v6.9.4-linux-x64/bin/node" "/opt/ibm/node-v6.9.4-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/asif/l/node_modules/ffi-napi
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/asif/l/package.json'
npm WARN l No description
npm WARN l No repository field.
npm WARN l No README data
npm WARN l No license field.
npm ERR! Linux 4.4.0-133-generic
npm ERR! argv "/opt/ibm/node-v6.9.4-linux-x64/bin/node" "/usr/local/bin/npm" "install" "ffi-napi"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ffi-napi@2.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@2.4.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi-napi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi-napi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffi-napi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/asif/l/npm-debug.log

I see this issue -
https://github.com/nodejs/node-addon-api/issues/387

**Comment by mkundgol** [comment]
@addaleax - could you merge this PR pls 
https://github.com/node-ffi-napi/node-ffi-napi/pull/26

**Comment by addaleax** [comment]
Published in `2.4.4`, let me know if you have any more problems!
