### ISSUE TITLE
Both are relative paths, but there was an error

### ISSUE THREAD

**Issue by BreezeIce6** [node-ffi-napi/node-ffi-napi#277]
project :
- demo
  - ocr
    - OCR_Module.dll 
    - index.js 
  - index.js

**demo/index.js :**

const ffi = require('ffi-napi')
const path = require('path')

const demo = new ffi.Library('./ocr/OCR_Module.dll', {
	start: ['void', []]
})

node index.js

Error: Dynamic Linking Error: Win32 error 126

--------------------------------------------------------------------

**demo/ocr/index.js :**

const ffi = require('ffi-napi')
const path = require('path')

const demo = new ffi.Library('./OCR_Module.dll', {
	start: ['void', []]
})

node index.js

**normal**

question：Does the executed js need to be in the same directory as the DLL?

**Comment by waitingsong** [comment]
1. try full path
2. use relative path and set the current dir of ffi

https://github.com/node-ffi-napi/node-ffi-napi/issues/269

**Comment by BreezeIce6** [comment]
> 1. try full path
> 2. use relative path and set the current dir of ffi
> 
> #269

still error

**Comment by BreezeIce6** [comment]
The problem has been resolved，Add the ocr directory to the environment variable
