### ISSUE TITLE
Access volation while using ffi.Callback

### ISSUE THREAD

**Issue by inithink** [node-ffi-napi/node-ffi-napi#36]
I'm using ffi-napi to use windows api.
It is good at first time, but sometimes my app crashed.
After many tests, I found ffi.Callback create null pointer exception.
It doesn't problem at first time, but calling many time of my function cause exit code 0xC0000005 (access volation)

I attached code below. (This simple code cause problem.)

I really like this library. Please fix this problem.
```javascript
const ffi = require('ffi-napi');
const {DTypes} = require('win32-def');
const LOOP_COUNT = 10000;
const user32 = ffi.Library('user32', {
  EnumWindows: [DTypes.BOOL, [DTypes.POINT, DTypes.LPARAM]],
});

function enumWindows() {
  const fn = ffi.Callback(DTypes.BOOL, [DTypes.HWND, DTypes.LPARAM], ()=> {
    return false;
  });
  const result = user32.EnumWindows(fn, 0);
  console.log('EnumWindows -> done', result, fn.address());
}


for (let i = 0; i < LOOP_COUNT; i++) {
  enumWindows()
}
```

My develop enviroment:
Windows 10 Home (1809)
Visual Studio 2017
Node.js v8.15.0 (tested 11.9.0 too)

**Comment by gorunovanton** [comment]
Any updates on this? I've just checked this repro and it still crashes.
@addaleax, do you have any plans to fix callback-related crashes?
