### ISSUE TITLE
Please add support for am64/aarch64

### ISSUE THREAD

**Issue by sfrieske** [node-ffi-napi/node-ffi-napi#45]
Building fails when libffi is built on `4.19.71 ... aarch64 GNU/Linux`:
`
node-gyp rebuild:
...
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/steffen/workspace/ffi-napi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
../deps/libffi/src/x86/ffi.c: In function 'ffi_prep_args':
../deps/libffi/src/x86/ffi.c:62:31: error: 'FFI_TYPE_MS_STRUCT' undeclared (first use in this function); did you mean 'FFI_TYPE_STRUCT'?
        || ecif->cif->flags == FFI_TYPE_MS_STRUCT)

`

**Comment by rhenwood-arm** [comment]
@sfrieske : have you tried this patch: https://github.com/node-ffi-napi/node-ffi-napi/pull/44 ?

**Comment by sfrieske** [comment]
I followed an instruction somewhere on the net how to install a current libffi version and make this module compile. This worked. Hoping the patch you reference will fix it for others.
