### ISSUE TITLE
[HELP] which thread does node-ffi-napi itself run in ?

### ISSUE THREAD

**Issue by bruceauyeung** [node-ffi-napi/node-ffi-napi#62]
scenario:
I have a JS function `A`, it invokes function `B` in my C library via `node-ffi-napi`.

I know func `A` runs in Node.js' main thread, but which thread does `node-ffi-napi`  itself run in ? and what about  function `B` in my C library?

if i try to invoke win32 api `GetCurrentThreadId ` via `node-ffi-napi`, can i get thread id of Node.js' main thread?

@addaleax  whould you please help me out, thanks !

**Comment by addaleax** [comment]
> I know func `A` runs in Node.js' main thread,

Well – unless you’re using Worker threads. :)

> but which thread does `node-ffi-napi` itself run in ? and what about function `B` in my C library?

By default, all calls happen on the same thread. You *can* specify functions to run on a separate thread (in libuv’s thread pool) using `.async`: https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial#async-library-calls

If you do need threading, I would however recommend to always use synchronous calls, and use Worker threads to get the threading functionality you want.

> if i try to invoke win32 api `GetCurrentThreadId ` via `node-ffi-napi`, can i get thread id of Node.js' main thread?

Yes, that’s what it will return if you call it from the main thread :+1:

**Comment by bruceauyeung** [comment]
callback functions look like sort of different.
scenario:
`ffi.Callback` wraps my JS function `C` and the returned pointer is assigned to a function pointer D in my C library. Now i invoke the function identified by `D` in another thread `E` ( a thread started by my C library ), this invocation is blocked until function C  returns and function C is guaranteed to run in `Node.js`' main thread, right ? there looks like at least be two threads involved, and looks like part of `node-ffi-napi` runs in thread `E` and rest of it run in `Node.js`' main thread.
what about this scenario ?
