### ISSUE TITLE
Warning: N-API is an experimental feature and could change at any time.

### ISSUE THREAD

**Issue by rhulha** [node-ffi-napi/node-ffi-napi#74]
Hello Everyone,

we are seeing this warning when using FFI-NAPI instead of FFI.
Is there a way to suppress the warning ?

Thanks!

**Comment by vweevers** [comment]
You can upgrade node to a version where N-API is no longer experimental: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

**Comment by addaleax** [comment]
Yes – in all supported versions of Node.js (not just by this module but in general), N-API is no longer experimental. :+1:
