### ISSUE TITLE
There is a problem when i use ffi-napi@2.5.0

### ISSUE THREAD

**Issue by han-a1** [node-ffi-napi/node-ffi-napi#75]
rror: No native build was found for platform=win32 arch=x64 runtime=electron abi=73 uv=1 libc=glibc
    at Function.load.path (webpack:///./node_modules/node-gyp-build/index.js?:56:9)
    at load (webpack:///./node_modules/node-gyp-build/index.js?:21:30)
    at eval (webpack:///./node_modules/ref-napi/lib/ref.js?:8:111)
    at Object../node_modules/ref-napi/lib/ref.js (D:\code\electron\electron-vue-demo\dist_electron\index.js:1266:1)
    at __webpack_require__ (D:\code\electron\electron-vue-demo\dist_electron\index.js:20:30)
    at eval (webpack:///./node_modules/ffi-napi/lib/ffi.js?:7:13)
    at Object../node_modules/ffi-napi/lib/ffi.js (D:\code\electron\electron-vue-demo\dist_electron\index.js:226:1)
    at __webpack_require__ (D:\code\electron\electron-vue-demo\dist_electron\index.js:20:30)
    at eval (webpack:///./src/background.js?:92:13)
    at Module../src/background.js (D:\code\electron\electron-vue-demo\dist_electron\index.js:1571:1)
 WARN  Force killing Electron (process #8972)

**Comment by GZhiDao1010** [comment]
@han-a1  so am i

**Comment by Liupeng8** [comment]
I have the same problem

**Comment by addaleax** [comment]
@han-a1 @GZhiDao1010 @Liupeng8 Would any one of you be able to provide steps to reproduce? Otherwise this issue is not actionable.

**Comment by han-a1** [comment]
> @han-a1 @GZhiDao1010 @Liupeng8 Would any one of you be able to provide steps to reproduce? Otherwise this issue is not actionable.

1. vue create electron-vue-demo
2. vue add electron-builder 
3.npm i ffi-napi -S 
4.require('ffi-napi')
When I compile the project, I report the above error

**Comment by Razviar** [comment]
same here, Electron 8.2.5 getting error

Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=76 uv=1 libc=glibc

**Comment by Razviar** [comment]
Pinging on this. Issue persists in 3.0.1
Steps to replicate:
1. Create basic Electron app, for instance "npx create-electron-app my-app"
2. import {Library} from 'ffi-napi';
3. Do anything with Library
4. Get something like this:

Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc
    at Function.module.exports../node_modules/node-gyp-build/index.js.load.path (D:\mtgap\.webpack\main\index.js:46258:9)
    at load (D:\mtgap\.webpack\main\index.js:46223:30)
    at Object../node_modules/ref-napi/lib/ref.js (D:\mtgap\.webpack\main\webpack:\node_modules\ref-napi\lib\ref.js:8:52)
    at __webpack_require__ (D:\mtgap\.webpack\main\webpack:\webpack\bootstrap:19:1)
    at Object../node_modules/ffi-napi/lib/ffi.js (D:\mtgap\.webpack\main\webpack:\node_modules\ffi-napi\lib\ffi.js:7:13)
    at __webpack_require__ (D:\mtgap\.webpack\main\webpack:\webpack\bootstrap:19:1)
    at Module../src/our-active-win/lib/windows.js (D:\mtgap\.webpack\main\webpack:\src\our-active-win\lib\windows.js:1:1)
    at __webpack_require__ (D:\mtgap\.webpack\main\webpack:\webpack\bootstrap:19:1)
    at Function.module.exports../src/our-active-win/index.js.module.exports.sync (D:\mtgap\.webpack\main\webpack:\src\our-active-win\index.js:29:10)
    at WindowLocator.module.exports../src/app/locatewindow.ts.WindowLocator.findmtga (D:\mtgap\.webpack\main\webpack:\src\app\locatewindow.ts:41:40)

**Comment by tyust512** [comment]
@addaleax 
thanks for your coming. Do you reproduce the problem? Do you have any idea? 
If have, can you say something. 
Waiting your message. 
Thanks your time and patience.

**Comment by tyust512** [comment]
@Razviar 
hi Razviar, do you resolve the problem? 
When i use https://github.com/SimulatedGREG/electron-vue to create the vue project, this error will reproduce.
But when i only use the demo: https://github.com/wzdxy/electron-ffi-demo , and i update the electron@9.0.0 / ffi-napi@3.0.1, the demo still works well. I guess the problem has relation with webpack or vue. But i don't know how to corret the problem.

I tryed to require('ffi-napi') in  public/index.html, in the dev mode, the ffi-napi works well. But when i use https://nklayman.github.io/vue-cli-plugin-electron-builder/ to build the exe. When i open the exe, the html will report one error: Module._resolveFilename (internal/modules/cjs/loader.js:797)

**Comment by tyust512** [comment]
I resolved this problem by change the externals options of webpack in vue.config.js.
The document says if there is an error, setting the native dependency as an webpack external.
Here is the document link: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#table-of-contents

Here is the content of vue.config.js, i omit some private config.
Wish this can help someone.

`module.exports = {
  configureWebpack: {
    devtool: 'source-map',
  },
  chainWebpack: config => {
    config.resolve.alias
      .set('root', resolve('./'))
      .set('~', resolve('src'))
      .set('@', resolve('src/renderer'))
      .set('@shared', resolve('src/shared'))
      .set('@utils', resolve('src/utils'))
  },
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      customFileProtocol: 'meelauncher://./',
      externals: ['ffi-napi'],
	}
  }
}`

**Comment by addaleax** [comment]
Thanks @tyust512!

It definitely makes sense that webpack has to be told how to handle native addons like this.

I hope this helps others here as well!

**Comment by Razviar** [comment]
Unfortunately, making module external is not quite a solution. When you build your app and package it for production, that module will be missing and whole setup won't work

**Comment by addaleax** [comment]
@Razviar The thing is, I don’t know a better solution, and if there’s one, that’s probably not a problem specifically with this module here either – it relates to how webpack packages your application and how Electron runs it.

**Comment by tyust512** [comment]
@Razviar 
i have package it for production, that module is still here. the app works well.

I write `const ffi = require('ffi-napi')` in the renderer vue file not main thread files

i set builderOptions.extraFiles to ['dll'] in `vue.config.js`，Here is the config:

builderOptions: { // https://www.electron.build/configuration/configuration
        productName: '智联云教育',
        appId: 'com.jd.mee-launcher',
        nodeGypRebuild: false, 
        asar: true,
        extraFiles: [ 
          'dll'
        ], // copy dll files to the root directory https://www.electron.build/configuration/contents#extrafiles


my package.json is here, you can change your electron / vue-cli versions to the same

`{
  "name": "launcher",
  "version": "0.0.1",
  "description": "云教育",
  "homepage": "",
  "author": {
    "name": "云教育",
    "email": ""
  },
  "license": "",
  "private": true,
  "main": "background.js",
  "scripts": {
    "serve": "vue-cli-service electron:serve",
    "build": "vue-cli-service electron:build",
    "all": "vue-cli-service electron:all",
    "lint": "vue-cli-service lint",
    "release": "vue-cli-service electron:build --publish always",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps",
    "build-icon": "electron-icon-builder --input=./public/icon.png --output=build --flatten"
  },
  "dependencies": {
    "@sentry/electron": "^1.3.0",
    "axios": "^0.19.2",
    "electron-dl": "^3.0.1",
    "electron-log": "^4.2.0",
    "electron-updater": "^4.3.1",
    "element-ui": "^2.9.1",
    "ffi-napi": "^3.0.1",
    "fs-extra": "^9.0.0",
    "i18next": "^19.4.4",
    "js-cookie": "^2.2.0",
    "jsonp": "^0.2.1",
    "lodash": "^4.17.15",
    "lowdb": "^1.0.0",
    "node-gyp": "^7.0.0",
    "vue": "^2.6.10",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.3",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.3"
  },
  "devDependencies": {
    "@commitlint/cli": "^8.3.5",
    "@commitlint/config-conventional": "^8.3.4",
    "@vue/cli-plugin-babel": "~4.2.0",
    "@vue/cli-plugin-eslint": "~4.2.0",
    "@vue/cli-plugin-router": "~4.2.0",
    "@vue/cli-plugin-vuex": "~4.2.0",
    "@vue/cli-service": "~4.2.0",
    "@vue/eslint-config-standard": "^5.1.0",
    "babel-eslint": "^10.0.3",
    "babel-plugin-component": "^1.1.1",
    "conventional-changelog": "^3.1.21",
    "cross-env": "^7.0.2",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.0.0",
    "electron-icon-builder": "^1.0.2",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.1.2",
    "image-webpack-loader": "^6.0.0",
    "lint-staged": "^10.2.7",
    "node-sass": "^4.12.0",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-electron-builder": "^1.4.6",
    "vue-template-compiler": "^2.6.11"
  },
  "gitHooks": {
    "pre-commit": "lint-staged",
    "commit-msg": "commitlint -E GIT_PARAMS"
  },
  "lint-staged": {
    "*.{js,vue,css}": [
      "vue-cli-service lint",
      "git add"
    ]
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ],
    "rules": {
      "type-enum": [
        2,
        "always",
        [
          "feat",
          "fix",
          "docs",
          "style",
          "refactor",
          "perf",
          "test",
          "revert",
          "build",
          "chore"
        ]
      ],
      "type-empty": [
        0
      ]
    }
  },
  "__npminstall_done": false
}`

you can show us your error stack, we will help you.

**Comment by andrew-oreshko** [comment]
I have the same issue, with both "ref-napi" and "ffi-napi" when running packaged production version, @Razviar.
https://github.com/node-ffi-napi/ref-napi/issues/46. And I asked for support here https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2588

**Comment by xiajingren** [comment]
Use in the electron main process：
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc node=12.14.1 electron=9.3.1 webpack=true
    loaded from: D:\WorkSpace\Temp\ele-vue
    at Function.load.path (webpack:///./node_modules/node-gyp-build/index.js?:59:9)
    at load (webpack:///./node_modules/node-gyp-build/index.js?:21:30)
    at eval (webpack:///./node_modules/ref-napi/lib/ref.js?:8:111)
    at Object../node_modules/ref-napi/lib/ref.js (D:\WorkSpace\Temp\ele-vue\dist_electron\index.js:1782:1)
    at __webpack_require__ (D:\WorkSpace\Temp\ele-vue\dist_electron\index.js:20:30)
    at eval (webpack:///./node_modules/ffi-napi/lib/ffi.js?:7:13)
    at Object../node_modules/ffi-napi/lib/ffi.js (D:\WorkSpace\Temp\ele-vue\dist_electron\index.js:790:1)
    at __webpack_require__ (D:\WorkSpace\Temp\ele-vue\dist_electron\index.js:20:30)
    at eval (webpack:///./src/winAPI.js?:3:66)
    at Module../src/winAPI.js (D:\WorkSpace\Temp\ele-vue\dist_electron\index.js:2063:1)


but in electron renderer process it's working.  why  ???

**Comment by johnzhu12** [comment]
+1

**Comment by johnzhu12** [comment]
as @tyust512 mentioned
I added the below line code in webpack.config.js

```js
module.exports ={
externals: {'ffi-napi':'require("ffi-napi")','ref-napi':'require("ref-napi")'},
....
}
```
then all works fine

**Comment by Razviar** [comment]
Unfortunately, nothing helped to solve my issue. Adding externals didn't help either. After I upgrade "ffi-napi" higher then "2.4.6" and ref-napi higher then 1.4.3, all I get is "No native build was found". I still have to use older packages, which work without any issues.

**Comment by johnzhu12** [comment]
in production mode ffi-napi and ref-api will not be compiled in bundle.js。so when I run build,I just use shell to copy these two modules into resource/app/node_modules/
