### ISSUE TITLE
aarch64 binary release

### ISSUE THREAD

**Issue by odidev** [node-ffi-napi/node-ffi-napi#77]
Hi Team,

The aarch64 architecture is already supported by node-ffi-napi, I would like to know what is required to be done in order to get aarch64 prebuilt binary release.

Please share your thoughts on this and let me know if anything could be done from my end to achieve this.

**Comment by addaleax** [comment]
@odidev I’m guessing all that’s strictly necessary would be a CI service that supports aarch64, that we could use in a similar fashion like we currently use Travis/Appveyor? Not really more than that.

We might also be able to cross-compile, but without CI runs that doesn’t seem like it’s really something to be called “supported”, so I’d be careful about that.

Also, I guess it’s relevant which OSes you’re looking for?

**Comment by odidev** [comment]
@addaleax Travis-ci now supports aarch64, if you agree I can work on adding aarch64 support in Travis-ci and raise a PR accordingly.

**Comment by odidev** [comment]
@addaleax Raised a pull request have a look, and do revert if something needs to be done from my end: https://github.com/node-ffi-napi/node-ffi-napi/pull/78.

**Comment by addaleax** [comment]
Okay, this should be done on the most recent versions all 3 relevant libraries now, please try it out and let me know if it works for you!
