### ISSUE TITLE
hi any idea about build ``` 'napi_is_date': identifier not found (```

### ISSUE THREAD

**Issue by godtoy** [node-ffi-napi/node-ffi-napi#79]
```
node v11.0.0
node-gyp@5.1.1
msbuild @vs2017
```
![image](https://user-images.githubusercontent.com/13638996/83106263-be161400-a0ee-11ea-8eb5-a75250000e54.png)

**Comment by godtoy** [comment]
when i use command to install new ffi modules 
```
npm install ffi-napi
```

but it's work on ```2.5.0``` version

**Comment by addaleax** [comment]
Node 11.x has been [unsupported for a year now](https://github.com/nodejs/Release#release-schedule) and has known security issues, please don’t use it. ffi-napi@3.x simply doesn’t support Node 11.x.
