### ISSUE TITLE
How to require ref and struct in ffi-napi

### ISSUE THREAD

**Issue by JqiangLiu** [node-ffi-napi/node-ffi-napi#81]
i cant find exports of ref in ffi.js. so do i need to extra install?

**Comment by addaleax** [comment]
Yes. Specifically, you’ll want `ref-napi` rather than `ref`, and you want `ref-struct-di` instead of `ref-struct`. You can use those as

```js
var ref = require('ref-napi')
var struct = require('ref-struct-di')(ref)
```
