### ISSUE TITLE
Can i use ffi-napi load .a or .framework on macOS platform?

### ISSUE THREAD

**Issue by jazzwsr** [node-ffi-napi/node-ffi-napi#90]
As mentioned above, I have a library written in c++. Can I load the library on the MAC and call the functions in the library?

**Comment by addaleax** [comment]
You can load any shared library files. `.a` or `.framework`s are not shared libraries, so, no, ffi-napi does not support that (although turning a `.a` file into a `.so` file is just a single compilation step, e.g. `clang -fPIC -o dynlib.so -shared -nostdlib -Wl,--whole-archive staticlib.a`).

**Comment by jazzwsr** [comment]
> You can load any shared library files. `.a` or `.framework`s are not shared libraries, so, no, ffi-napi does not support that (although turning a `.a` file into a `.so` file is just a single compilation step, e.g. `clang -fPIC -o dynlib.so -shared -nostdlib -Wl,--whole-archive staticlib.a`)

 thanks!
