### ISSUE TITLE
npm i ffi-napi failed in version(3.0.1, latest), and success in version(2.5.0) 

### ISSUE THREAD

**Issue by gzx-miller** [node-ffi-napi/node-ffi-napi#91]
Environment: win 10, vs2017, node-gyp.

npm i ffi-napi@latest --arch=ia32

> ref-napi@2.0.3 install E:\code\nodeJS\node_test\node_modules\ref-napi
> node-gyp-build

> ffi-napi@3.0.1 install E:\code\nodeJS\node_test\node_modules\ffi-napi
> node-gyp-build

在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Building assembly file ..\..\..\deps\libffi\src\x86\win32.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> E:\code\nodeJS\node_test\node_modules\ffi-napi\build\Release\\libffi.lib
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> E:\code\nodeJS\node_test\node_modules\ffi-napi\build\Release\\nothing.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
e:\code\nodejs\node_test\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(416): error C3861: “napi_is_da
te”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [E:\code\nodeJS\node_test\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
e:\code\nodejs\node_test\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(711): error C3861: “napi_creat 
e_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [E:\code\nodeJS\node_test\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
e:\code\nodejs\node_test\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(728): error C3861: “napi_get_d
ate_value”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [E:\code\nodeJS\node_test\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
e:\code\nodejs\node_test\node_modules\ffi-napi\src\ffi.cc(11): error C3861: “napi_get_instance_data”: 找不到标识符 [E:\cod
e\nodeJS\node_test\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
e:\code\nodejs\node_test\node_modules\ffi-napi\src\ffi.cc(347): error C3861: “napi_set_instance_data”: 找不到标识符 [E:\co
de\nodeJS\node_test\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\code\nodeJS\node_test\node_modules\node-gyp\lib\build.js:194:23)       
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\code\\nodeJS\\node_test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\code\nodeJS\node_test\node_modules\ffi-napi
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm WARN node_test@1.0.0 No description
npm WARN node_test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by gzx-miller** [comment]
I find it's caused by node version too low,  the version need update to 12.18.3.

**Comment by waitingsong** [comment]
Maybe version of python is too old (2.7), not supported by  3.x of ffi-napi.
