### ISSUE TITLE
I set callback from js, and call this callback from dll, it success at first time, it cause webpage hang in second time.

### ISSUE THREAD

**Issue by gzx-miller** [node-ffi-napi/node-ffi-napi#92]
Environment: Electron9.1.0, win 10, vs2017, node-gyp, ffi-napi@2.5.0

    // app.js
    window.ffi_napi = ffi.Library("./my_win.dll", {
      set_callback: ['void', ['pointer']]
    });
    var c_CallBack = ffi.Callback('int', ['int'], 
      function(id) {
        console.log(`[callback] ${id}`);
        return 456;
      });
    process.on('exit', () => {
      c_CallBack // keep reference avoid gc
    })
    // call setCallback
    window.ffi_napi.set_callback(c_CallBack);
    
    // .h
    typedef int (*PFCallback)(int);
    DLL_API void set_callback(PFCallback cb);

    // .cpp
    PFCallback g_cb = nullptr;
    DLL_API void set_callback(PFCallback cb) {
        g_cb = cb;
    }
    void threadProc() {
        sprintLog("callback begin: %x \r\n", g_cb);
        if (g_cb) {
            int ret = g_cb(123);
        }
    }
    threadProc();

**Comment by gzx-miller** [comment]
Use the the version 3.0.1, can fix this problem.

**Comment by bruceauyeung** [comment]
@gzx-miller Does this bug exist in version 2.4.7?
