### ISSUE TITLE
install 3.0.0  Error

### ISSUE THREAD

**Issue by XiaohuiSu** [node-ffi-napi/node-ffi-napi#93]
@2.5.0 's codes are OK
@3.0.0 not
System : windows10

$ npm install -g ffi-napi@3.0.0 

> ref-napi@2.1.1 install C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\node_modules\ref-napi
> node-gyp-build

> ffi-napi@3.0.1 install C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi
> node-gyp-build

在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.cc
  ffi.vcxproj -> C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\Release\\libffi.lib
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\Release\\nothing.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.cc
c:\users\xiaohuisu\appdata\roaming\npm\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(416): error C3861:
“napi_is_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\ffi_bi
ndings.vcxproj]
c:\users\xiaohuisu\appdata\roaming\npm\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(711): error C3861:
“napi_create_date”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\ff
i_bindings.vcxproj]
c:\users\xiaohuisu\appdata\roaming\npm\node_modules\ffi-napi\node_modules\node-addon-api\napi-inl.h(728): error C3861:
“napi_get_date_value”: 找不到标识符 (编译源文件 ..\src\ffi.cc) [C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build
\ffi_bindings.vcxproj]
c:\users\xiaohuisu\appdata\roaming\npm\node_modules\ffi-napi\src\ffi.cc(11): error C3861: “napi_get_instance_data”: 找不到
标识符 [C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
c:\users\xiaohuisu\appdata\roaming\npm\node_modules\ffi-napi\src\ffi.cc(347): error C3861: “napi_set_instance_data”: 找不
到标识符 [C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xiaohuisu\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\xiaohuisu\AppData\Roaming\npm\node_modules\ffi-napi
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xiaohuisu\AppData\Roaming\npm-cache\_logs\2020-08-28T11_44_39_446Z-debug.log

**Comment by acdibble** [comment]
![image](https://user-images.githubusercontent.com/21286068/91585324-38f00480-e954-11ea-92b1-d8bf87859b7d.png)
You need to upgrade to a node version >= 10.20.0

**Comment by XiaohuiSu** [comment]
> ![image](https://user-images.githubusercontent.com/21286068/91585324-38f00480-e954-11ea-92b1-d8bf87859b7d.png)
> You need to upgrade to a node version >= 10.20.0

OK~ thanks
